# Generated by Django 4.0.6 on 2022-12-15 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('profile_options', models.IntegerField()),
                ('user_age', models.IntegerField()),
                ('date_created', models.DateField()),
                ('group_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='expense_tracking.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('store_id', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('purchase_total', models.FloatField()),
                ('purchase', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking.users')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_description', models.CharField(max_length=80)),
                ('product_quantity', models.FloatField()),
                ('product_unit_price', models.FloatField()),
                ('product_total_price', models.FloatField()),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking.purchases')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_text', models.CharField(max_length=80)),
                ('amount', models.FloatField()),
                ('purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_tracking.purchases')),
            ],
        ),
    ]
